# Generated by Django 3.1.4 on 2020-12-03 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201203_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailuser',
            name='password',
            field=models.CharField(blank=True, max_length=100, verbose_name="user's password"),
        ),
    ]
