# Generated by Django 3.1.4 on 2020-12-04 08:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20201204_1228'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailuser',
            options={'verbose_name': '邮箱用户', 'verbose_name_plural': '邮箱用户'},
        ),
        migrations.AddField(
            model_name='emailuser',
            name='is_actived',
            field=models.BooleanField(default=False, verbose_name='是否激活'),
        ),
        migrations.AddField(
            model_name='emailuser',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='是否验证'),
        ),
        migrations.AlterField(
            model_name='emailuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='emailuser',
            name='email',
            field=models.EmailField(max_length=255, verbose_name='用户邮箱'),
        ),
        migrations.AlterField(
            model_name='emailuser',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='用户ID'),
        ),
        migrations.AlterField(
            model_name='emailuser',
            name='password',
            field=models.CharField(blank=True, max_length=100, verbose_name='用户密码'),
        ),
        migrations.AlterField(
            model_name='emailuser',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='emailuser',
            name='username',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='用户名'),
        ),
    ]
