# Generated by Django 3.1.4 on 2020-12-04 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20201204_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailuser',
            name='email',
            field=models.EmailField(max_length=255, unique=True, verbose_name='用户邮箱'),
        ),
    ]
