# Generated by Django 3.1.4 on 2020-12-04 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20201204_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailuser',
            name='avatar',
            field=models.ImageField(blank=True, default='', null=True, upload_to='avatar/', verbose_name="user's avater"),
        ),
    ]
